image: localhost:5000/centos-7-fuglu-testenv

stages:
  - build
  - test
  - build_py3
  - test_py3

unittests:
  stage: test
  script:
    - cd fuglu
    - nosetests --rednose tests/unit
  only:
    - master
    - develop

unittests_py3:
  stage: test_py3
  script:
    - cd fuglu
    - nosetests-3.4 --rednose tests/unit
  only:
    - master
    - develop

integrationtests:
  stage: test
  script:
    - sh /usr/local/bin/start-services.sh
    - cat clamd.log
    - cat spamd.log
    - cd fuglu
    - nosetests --rednose tests/integration
  only:
    - master
    - develop

integrationtests_py3:
  stage: test_py3
  script:
    - sh /usr/local/bin/start-services.sh
    - cat clamd.log
    - cat spamd.log
    - cd fuglu
    - nosetests-3.4 --rednose tests/integration
  only:
    - master
    - develop


# define RSYNC_TARGET in gitlab -> project domainmagic -> settings -> variables

buildfuglu:
  stage: build
  script:
    - cd fuglu 
    - python setup.py build_py -d /tmp/build install --force
    - rename '.dist' '' /etc/fuglu/*.dist
    - mkdir -p /var/log/fuglu
    - chown nobody /var/log/fuglu
  only:
    - master
    - develop

buildfuglu_py3:
  stage: build_py3
  script:
    - cd fuglu 
    - python3 setup.py build_py -d /tmp/build install --force
    - rename '.dist' '' /etc/fuglu/*.dist
    - mkdir -p /var/log/fuglu
    - chown nobody /var/log/fuglu
  only:
    - master
    - develop
