language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unrar

install:
  - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then pip install ipaddr; fi
  - pip install -r fuglu/tests/travis/test-requirements.txt

script: nosetests fuglu/tests/unit/

branches:
  only:
    - master

notifications:
  email: true
  
cache:
  apt: true
