language: python
python:
  - "2.6"
  - "2.7"
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clamav-daemon spamassassin
  - sudo spamd -d
  - sudo freshclam
  - sudo service clamav-daemon restart
  
# command to install dependencies
install:
  - pip install -r fuglu/test/travis/test-requirements.txt
# command to run tests
script: python fuglu/test/runtests.py


branches:
  only:
    - master

notifications:
  email: true